### ISSUE TITLE
Не загружается кривая геометрия

### ISSUE THREAD

**Issue by drnextgis** [nextgis/barnaul_data_loader#10]
Хотя чекбокс отмечен. Пишет `Запись 0 с пустой или невалидной геометрией будет пропущена`. Открыл слой в QGIS - да, геометрия невалидная, но не пустая.
![2015-10-30 17 46 53](https://cloud.githubusercontent.com/assets/866124/10844959/d1294296-7f25-11e5-9a69-c93a886177a2.png)

**Comment by BishopGIS** [comment]
Так чекбокс снят должен был быть. Там же написано отметьте для пропуска невалидных геометрий.
Я проверил на входе 14 записей - на выходе столько же.

**Comment by drnextgis** [comment]
Можешь тогда переименовать этот пункт, а то я понял его совсем наоборот? Например в **Не загружать невалидные геометрии**.
