### ISSUE TITLE
Ошибка проекции

### ISSUE THREAD

**Issue by drnextgis** [nextgis/barnaul_data_loader#12]
Сейчас при переходе на импорт через GeoJSON данные улетают в Африку, в консоли ошибка:

```
ERROR 1: Full reprojection failed, but partial is possible if you define OGR_ENABLE_PARTIAL_REPROJECTION configuration option to TRUE
```

**Comment by BishopGIS** [comment]
Это особенность драйвера geojson в gdal - пока копать некогда сделаю костыль.
Особенность, что для слоя не возвращается СК.
