### ISSUE TITLE
Перевод типов геометрии

### ISSUE THREAD

**Issue by drnextgis** [nextgis/barnaul_data_loader#6]
Polygon и т. д.

**Comment by BishopGIS** [comment]
Непонятно что и куда надо переводить?
Сейчас происходит перевод геометрии к мультигеометрии соответствующего типа.

**Comment by drnextgis** [comment]
Я имел в виду перевод на русский элементов выпадающего списка.

**Comment by BishopGIS** [comment]
Fix in nextgismanager/15fe99dfb71fe2184477cf2343c71716be2d714c
