### ISSUE TITLE
Дефолтные параметры

### ISSUE THREAD

**Issue by drnextgis** [nextgis/barnaul_data_loader#9]
1) Чекбокс пропуска невалидных геометрий должен быть включен по умолчанию
2) Тип геометрии - если есть полигоны, то всегда по умолчанию выбирать его
3) Поля связи всегда одни и те же - **OID** для CSV и **RegisterNo** для MIF/MID - можно было бы, наверное, захардкодить эти названия, чтобы они выбирались автоматом, но если плагин сможет записывать последние значения этих полей и их потом подставлять в диалог создания и обновления, то это наверное даже лучше.

**Comment by BishopGIS** [comment]
1) Он как раз снят для добавления всех геометрий

**Comment by BishopGIS** [comment]
Closed via https://github.com/nextgis/barnaul_data_loader/commit/189a86d286166625275797bea768b97d7940bd06
